apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimirtool-reloader
  namespace: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimirtool
  template:
    metadata:
      labels:
        app: mimirtool
    spec:
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
      serviceAccountName: mimirtool-reloader
      containers:
        - name: mimirtool
          image: ekirmayer/mimir-reloader:amd64.26
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: "mimir"
            - name: ENV_ENDPOINT
              value: "http://mimir-ruler:8080"
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: shared-volume
              mountPath: /app/alerts
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: sidecar
          image: kiwigrid/k8s-sidecar:latest
          volumeMounts:
            - name: shared-volume
              mountPath: /tmp/
              readOnly: false
          env:
            - name: LABEL
              value: "findme"
            - name: FOLDER
              value: /tmp/
            - name: RESOURCE
              value: both
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: shared-volume
          emptyDir: {}
