apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mimirtool-reloader
  namespace: mimir
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]

